[package]
name = "sodo"
version = "0.2.2"
description = "Sudoku in Rust"
license = "MIT OR Apache-2.0"
readme = "../README.md"
edition = "2024"

[dependencies]
rand = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde"]
